apiVersion: apps/v1
kind: Deployment
metadata:
  name: gokub-tester
  labels:
    app: gokub-tester
spec:
  revisionHistoryLimit : 1
  template:
    metadata:
      name: gokub-tester
      labels:
        app: gokub-tester
    spec:
      containers:
      - name: gokub-tester
        livenessProbe:
          httpGet:
            path: /dev/gokub/health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
