apiVersion: v1
kind: Pod
metadata:
  name: gokub-tester
  labels:
    app: gokub-tester
spec:
  containers:
    - name: gokub-tester
      image: horvatic/gokub-tester
      ports:
        - containerPort: 8080
          name: "gokub-http"
