name: build-deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
        
    - name: Build
      run: go build -v cmd/gokub-tester/main.go
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        platforms: linux/arm64
        context: .
        file: ./Dockerfile
        push: true 
        tags: horvatic/gokub-tester:latest
  
    - name: 'Upload Deploy'
      uses: actions/upload-artifact@v2
      with:
        name: deploy
        path: deploy
        retention-days: 5
        
  dev:
    name: Deploy To Dev
    environment:
      name: dev
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Kubectl tool installer
      uses: Azure/setup-kubectl@v1
  
    - name: Setup kubectl
      env: 
        K8S_CONFIG: ${{ secrets.K8S_CONFIG }}
      run: |
        mkdir -p $HOME/.kube
        echo "${K8S_CONFIG}" | base64 --decode > $HOME/.kube/config
      
    - name: Download Deploy
      uses: actions/download-artifact@v2
      with:
        name: deploy
      
    - name: Delete pods
      run: kubectl delete -k dev -n dev
      continue-on-error: true
      
    - name: Apply pods
      run: kubectl apply -k dev -n dev
      
    - name: Wait for pods to start
      run: kubectl wait --for=condition=ready pod -l app=gokub-tester -n dev
      
